close all;
data = importdata('.\data\kresults_h+texture.txt');
x = data(1:end,1);
y1 = data(1:end,2); 
y2 = data(1:end,3);
y3 = data(1:end,4);
y4 = data(1:end,5);
figure(2);
plot(x,y1);
hold on;
plot(x,y2);
hold on;
plot(x,y3);
hold on;
plot(x,y4);
legend('cpu time during','overall accuracy','misclassification rate of natural','misclassification rate of manmade');
title('kresults H+Texture+LDA');
xlabel('k');
ylabel('parameter');